### ISSUE TITLE
problems in "route" and "shortcut" layers

### ISSUE THREAD

**Issue by WongKinYiu** [TommyHuang821/Visualization-for-Darknet-network-structure-#1]
您好
因為您多了一個input layer, 當route layer或shortcut layer的參數為正時, 似乎會少算1層.
另外當有shortcut layer接收來自大於2層時, 由於程式中設定pass, 所以會出錯.

**Comment by TommyHuang821** [comment]
hi 
我今天剛好發現[route]這邊有錯誤，的確因為input layer導致我少算一層(當[route]設定是正值時會少一層，這部分我剛update code上去了fun_parse_cfg)
我的code [route]部分如果有兩個值以上，我會用Concat去接，只有一個值我用shortcut去接
修改部分: fun_parse_cfg.py (Line 129-135)

2. shortcut layer接收來自大於2層時, 由於程式中設定pass
這邊我可能需要麻煩你提供範例code讓我看一下
因為我這邊用default都只有一個值，我沒有看過兩個值的


感謝你
Tommy

**Comment by WongKinYiu** [comment]
您好
以下為一簡單範例, 請參見
[net]
batch=64
subdivisions=64
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 50000
policy=steps
steps=40000,45000
scales=.1,.1

[convolutional]
batch_normalize=1
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=1

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[shortcut]
activation=leaky
from=8

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[shortcut]
activation=leaky
from=-3

[shortcut]
activation=leaky
from=8

以上

主要由於 pass
所以會發生類似[[a,b], c]要進行連線的問題
而[a,b]為list非integer
因此會發生例外

**Comment by TommyHuang821** [comment]
hi
short-cut 部分應該跟route發生一樣的問題，如果layer code是正數，在我放到all_layers list時應該要在+1
所以會抓錯層，導致問題發生。
修改部分: fun_parse_cfg.py (新上傳的Line 192-196，可以去看Commits)

然後這邊還是有一個問題，因為我這版純粹是為了快速看結構，所以很多case都沒有測試和寫check code
所以你貼的範例有一個問題是
你的shortcut接的兩層輸入是26 × 26 × 128和26 × 26 × 256，但程式還是能跑出輸出是26 × 26 × 128
這邊是錯的，因為26 × 26 × 128和26 × 26 × 256是不能做element-wise sum，理論上程式應該要寫check後給warning。
但我就沒空寫，你可能要注意一下。

**Comment by WongKinYiu** [comment]
您好
shortcut的實作是對齊-1層的維度逐元素相加
所以無論-1層與link層的width, height或是channel不一致都是合法的
您的visualization則是會輸出link層的維度喔
我會再注意
感謝您

**Comment by TommyHuang821** [comment]
感謝你幫忙找一些bug出來

我看code他實作是從*out和*add去做相加
channel、長寬都是小的去計算，雖然說計算合法程式不會出錯，但在算法裡面滿不合理的

我自己這份code都沒有做檢查code，例如shortcut就沒有check兩個feature map之間的channel數和長寬，理論上不太一樣程式應該給個warning。所以這部分可能也是要麻煩你們自己自己小心，不要太相信跑出來結構圖的結果。

void shortcut_cpu(int batch, int w1, int h1, int c1, float *add, int w2, int h2, int c2, float s1, float s2, float *out)
{
    int stride = w1/w2;
    int sample = w2/w1;
    assert(stride == h1/h2);
    assert(sample == h2/h1);
    if(stride < 1) stride = 1;
    if(sample < 1) sample = 1;
    int minw = (w1 < w2) ? w1 : w2;
    int minh = (h1 < h2) ? h1 : h2;
    int minc = (c1 < c2) ? c1 : c2;

    int i,j,k,b;
    for(b = 0; b < batch; ++b){
        for(k = 0; k < minc; ++k){
            for(j = 0; j < minh; ++j){
                for(i = 0; i < minw; ++i){
                    int out_index = i*sample + w2*(j*sample + h2*(k + c2*b));
                    int add_index = i*stride + w1*(j*stride + h1*(k + c1*b));
                    out[out_index] = s1*out[out_index] + s2*add[add_index];
                }
            }
        }
    }
}

**Comment by WongKinYiu** [comment]
好的
感謝您
